const baseFontStack = '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif';

const darkTheme = {
  colorAction: '#5E48FC',
  colorBackground: '#0A0A0C',
  colorBorder: '#68686C',
  colorDisabled: '#64646E',
  colorError: '#FF3300',
  colorFormBackground: '#1F1F1F',
  colorFormBorder: '#1F1F1F',
  colorInverse: '#F9F9FB',
  colorOutline: '#ADA4EC',
  colorPrimary: '#F9F9FB',
  colorSecondary: '#828388',
  colorSuccess: '#2ECC71',
  button: {
    fontFamily: `"Roboto Mono", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '24px',
  },
  footnote: {
    fontFamily: `"PT Sans", ${baseFontStack}`,
    fontSize: '14px',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  label: {
    fontFamily: `"Roboto Mono", ${baseFontStack}`,
    fontSize: '14px',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  subheading: {
    fontFamily: `"Roboto Mono", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '24px',
  },
  borderRadius: ['8px', '8px'],
};

const lightTheme = {
  colorAction: '#3B82F6',
  colorBackground: '#FFFFFF',
  colorBorder: '#D1D5DB',
  colorDisabled: '#9CA3AF',
  colorError: '#EF4444',
  colorFormBackground: '#F9FAFB',
  colorFormBorder: '#E5E7EB',
  colorInverse: '#1F2937',
  colorOutline: '#93C5FD',
  colorPrimary: '#1F2937',
  colorSecondary: '#6B7280',
  colorSuccess: '#10B981',
  button: {
    fontFamily: `"Lato", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '24px',
  },
  footnote: {
    fontFamily: `"Open Sans", ${baseFontStack}`,
    fontSize: '14px',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  label: {
    fontFamily: `"Lato", ${baseFontStack}`,
    fontSize: '14px',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  subheading: {
    fontFamily: `"Lato", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '24px',
  },
  borderRadius: ['8px', '8px'],
};

const neonTheme = {
  colorAction: '#FF00FF',
  colorBackground: '#1A1A1A',
  colorBorder: '#00FFFF',
  colorDisabled: '#555555',
  colorError: '#FF5555',
  colorFormBackground: '#222222',
  colorFormBorder: '#00FFFF',
  colorInverse: '#FFFFFF',
  colorOutline: '#FF00FF',
  colorPrimary: '#FFFFFF',
  colorSecondary: '#AAAAAA',
  colorSuccess: '#00FF00',
  button: {
    fontFamily: `"Exo 2", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '24px',
  },
  footnote: {
    fontFamily: `"Orbitron", ${baseFontStack}`,
    fontSize: '14px',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  label: {
    fontFamily: `"Exo 2", ${baseFontStack}`,
    fontSize: '14px',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  subheading: {
    fontFamily: `"Exo 2", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '24px',
  },
  borderRadius: ['12px', '12px'],
};

const sportTheme = {
  colorAction: '#FF4500',
  colorBackground: '#F5F6F5',
  colorBorder: '#333333',
  colorDisabled: '#888888',
  colorError: '#DC143C',
  colorFormBackground: '#FFFFFF',
  colorFormBorder: '#333333',
  colorInverse: '#000000',
  colorOutline: '#FF4500',
  colorPrimary: '#000000',
  colorSecondary: '#555555',
  colorSuccess: '#32CD32',
  button: {
    fontFamily: `"Bebas Neue", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '24px',
  },
  footnote: {
    fontFamily: `"Montserrat", ${baseFontStack}`,
    fontSize: '14px',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  label: {
    fontFamily: `"Bebas Neue", ${baseFontStack}`,
    fontSize: '14px',
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '20px',
  },
  subheading: {
    fontFamily: `"Bebas Neue", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: '24px',
  },
  borderRadius: ['6px', '6px'],
};

// NEW THEME: Minimal/Clean
const minimalTheme = {
  colorAction: '#007AFF',
  colorBackground: '#FAFAFA',
  colorBorder: '#E8E8E8',
  colorDisabled: '#C7C7CC',
  colorError: '#FF3B30',
  colorFormBackground: '#FFFFFF',
  colorFormBorder: '#F2F2F7',
  colorInverse: '#1C1C1E',
  colorOutline: '#007AFF',
  colorPrimary: '#1C1C1E',
  colorSecondary: '#8E8E93',
  colorSuccess: '#34C759',
  button: {
    fontFamily: `"Inter", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 500,
    letterSpacing: '-0.01em',
    lineHeight: '24px',
  },
  footnote: {
    fontFamily: `"Inter", ${baseFontStack}`,
    fontSize: '13px',
    fontWeight: 400,
    letterSpacing: '-0.01em',
    lineHeight: '18px',
  },
  label: {
    fontFamily: `"Inter", ${baseFontStack}`,
    fontSize: '14px',
    fontWeight: 500,
    letterSpacing: '-0.01em',
    lineHeight: '20px',
  },
  subheading: {
    fontFamily: `"Inter", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 600,
    letterSpacing: '-0.01em',
    lineHeight: '24px',
  },
  borderRadius: ['12px', '12px'],
};

// NEW THEME: Luxury/Premium
const luxuryTheme = {
  colorAction: '#D4AF37',
  colorBackground: '#FEFEFE',
  colorBorder: '#E5E0D8',
  colorDisabled: '#B8B5B2',
  colorError: '#B22222',
  colorFormBackground: '#FEFDFB',
  colorFormBorder: '#E8E3DC',
  colorInverse: '#2C2B28',
  colorOutline: '#D4AF37',
  colorPrimary: '#2C2B28',
  colorSecondary: '#8B8680',
  colorSuccess: '#228B22',
  button: {
    fontFamily: `"Playfair Display", ${baseFontStack}`,
    fontSize: '16px',
    fontWeight: 600,
    letterSpacing: '0.02em',
    lineHeight: '24px',
  },
  footnote: {
    fontFamily: `"Source Sans Pro", ${baseFontStack}`,
    fontSize: '13px',
    fontWeight: 400,
    letterSpacing: '0.01em',
    lineHeight: '18px',
  },
  label: {
    fontFamily: `"Source Sans Pro", ${baseFontStack}`,
    fontSize: '14px',
    fontWeight: 500,
    letterSpacing: '0.01em',
    lineHeight: '20px',
  },
  subheading: {
    fontFamily: `"Playfair Display", ${baseFontStack}`,
    fontSize: '18px',
    fontWeight: 600,
    letterSpacing: '0.02em',
    lineHeight: '26px',
  },
  borderRadius: ['4px', '4px'],
};

export const themes = {
  dark: darkTheme,
  light: lightTheme,
  neon: neonTheme,
  sport: sportTheme,
  minimal: minimalTheme,
  luxury: luxuryTheme,
};